---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP
  name: DEPLOYMENTNAME
  namespace: NAMESPACE
spec:
  selector:
    matchLabels:
      app: APP
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: APP
    spec:
      volumes:
        - name: timezone-configuration
          hostPath:
            path: /usr/share/zoneinfo/Africa/Nairobi
      containers:
        - name: APP
          image: ImageName
          ports:
            - containerPort: PORT
          imagePullPolicy: IfNotPresent
          env:
           - name: SPRING_PROFILES_ACTIVE
             value: SPRINGPROFILE
           - name: TZ
             value: Africa/Nairobi          
          volumeMounts:
          - name: timezone-configuration
            mountPath: /etc/localtime
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 192.168.3.215
          - 8.8.8.8            
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: NAMESPACE
  labels:
    run: SERVICENAME
spec:
  type: NodePort
  ports:
    - name: PORTNAME
      port: PORT
      protocol: TCP
  selector:
    app: APP
